# Site settings
title: "Sean Sperte"
email: sean@sperte.com
description: >
  Product designer. Leading design at Pinwheel; previously founding designer at Passbook (Remitly), co-founder of Tagboard.
baseurl: ""
url: "https://seansperte.com"
twitter_username: sperte
github_username: sperte

# Build settings
permalink: /entry/:title
paginate: 10
paginate_path: "/:num"
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

# Plugins
# gems:
  # - jekyll-redirect-from
