# Site settings
title: "Sean Sperte"
email: sean@sperte.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. Welcome to the weblog of Sean Sperte. This is a collection of notes related to design, technology, and faith.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seansperte.com" # the base hostname & protocol for your site
twitter_username: sperte
github_username: sperte

# Build settings
permalink: /entry/:title
paginate: 10
paginate_path: "/:num"
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-redirect-from